FROM node:22-alpine AS base

RUN apk update && apk add --no-cache libc6-compat
RUN corepack enable && corepack prepare pnpm@latest --activate
ENV PNPM_HOME="/pnpm"
ENV PATH=$PNPM_HOME:$PATH
ENV CI=true
ENV DIR=usr/src/app
WORKDIR $DIR


FROM base AS build
ENV NODE_ENV=development
COPY package.json .
COPY pnpm-lock.yaml .

RUN pnpm install

COPY tsconfig*.json .
COPY .swcrc .
COPY nest-cli.json .    
COPY src ./src

EXPOSE $PORT

CMD ["pnpm", "run", "start:dev"]

